### ISSUE TITLE
MacOS Error

### ISSUE THREAD

**Issue by hasantahir** [ForeignGods/Sorting-Algorithms-Blender#6]
Hi,

Thanks for making this available for everyone. I wanted to know if there are any Blender version requirements for this to use. On Blender 3.6, I get the following error whilst running `bubble_sort_scale.py`:

```
Python: Traceback (most recent call last):
  File "~/Downloads/sort.blend/bubble_sort_scale.py", line 150, in <module>
  File "~/Downloads/sort.blend/bubble_sort_scale.py", line 71, in setup_array
IndexError: bpy_prop_collection[-1]: out of range.
```
Line 71 is:

```
# get and clear node_group
node_grp = bpy.data.node_groups[-1] 
```

whereas line 150 is:

```
cubes, arrayCounter, comparisonCounter = setup_array(50)
```

Looking forward to your reply.

Thanks

**Comment by hasantahir** [comment]
I am on a Mac machine (MacOS 14.0, Blender 3.6.5). The Python details are:
`PYTHON INTERACTIVE CONSOLE 3.10.13 (main, Oct  6 2023, 17:59:10) [Clang 14.0.3 (clang-1403.0.22.14.1)]`

Notably, on a Linux machine, it runs fine.
